### ISSUE TITLE
IE redirect_uri route mount issue

### ISSUE THREAD

**Issue by vdveer** [soukoku/vue-oidc-client#11]
Thanks for creating this library!

When using this library (transpiled) in IE, the callback-uri might be mounted to an incorrect route. In the `getUrlPath(url)` method there is already some code to help coping with the fact that IE omits the leading `/` in the path name. This is also where the bug seems to be, as when the path does not start with a `/`, a trailing `/` will be added. Will open a PR for this.

**Comment by vdveer** [comment]
https://github.com/soukoku/vue-oidc-client/pull/12

**Comment by soukoku** [comment]
Wow can't believe I made this error. Thanks for the fix. Version 0.3.1 should have this fix.
