### ISSUE TITLE
typescript bindings not being packaged in npm due to package.json config

### ISSUE THREAD

**Issue by stephlocke** [soukoku/vue-oidc-client#28]
## Problem
npm pulled package does not have full typescript bindings

## Cause
There's a full typescript binding written in `src/VueOidcAuth.d.ts` however, itis being stripped out of the distributed package due to package.json settings

- The package.json references the "typings" at [L10](https://github.com/soukoku/vue-oidc-client/blob/master/package.json#L10) - ts files are excluded from src at [L13](https://github.com/soukoku/vue-oidc-client/blob/master/package.json#L13).

## Suggested fix
The .ts extension should be allowed in L13 of package.json 

## Workaround
In the interim I took the file and added it to my own src/ dir. I then wrapped the contents in `declare module "vue-oidc-client" {}`.

**Comment by soukoku** [comment]
Fixed in v0.4.1

**Comment by stephlocke** [comment]
Thanks for the rapid fix :)
