### ISSUE TITLE
UserManager.getUser: user not found in storage

### ISSUE THREAD

**Issue by Tigger151515** [soukoku/vue-oidc-client#30]
Hi. I did all by documentation, but now I have few problems
1. UserManager.getUser: user not found in storage. 

Storage like this:

```
length: 278
loglevel:webpack-dev-server: "SILENT"
oidc.0a6184cef9694f76aa314a2cb87d5738: "{"id":"0a6184cef9694f76aa314a2cb87d5738","data":{"to":{"meta":{"authName":"main"},"path":"/ru/profile","hash":"","query":{"state":"741fdf769fdd42a3b6ad63fc0f60a49e","session_state":"f48204f8....
```

2. then i have this message 
UserManager.signinRedirect: successful

and infinite redirect

**Comment by xesjkeee** [comment]
Have same issue

**Comment by miguelpuiggarcia** [comment]
same here...

**Comment by invokermain** [comment]
Shot in the dark... try using: `userStore: new WebStorageStateStore({ store: window.localStorage })` in your oidc config? I might have had the same issue and fixed it with this, or I could be misremembering.

**Comment by conundrumjwb** [comment]
Tried invokermain solution still inf. redirects, any solutions?
