### ISSUE TITLE
Release for Missing Log Level Typings

### ISSUE THREAD

**Issue by jculverwell** [soukoku/vue-oidc-client#6]
I noticed you added this commit `Missed exporting LogLevel definition.` 26 days ago but there has not been a release since.  I just tried to use the library today using typescript and it complained about the LogLevel.  Do you need to do another release to fix this or should should I be doing something my end?

P.S. Thanks for a great lib

**Comment by soukoku** [comment]
Finally got around to it in 0.3 for what it's worth.
