### ISSUE TITLE
SignOut() with SignInType.Window does not redirect properly when on authenticated route

### ISSUE THREAD

**Issue by MisterFab1an** [soukoku/vue-oidc-client#62]
When a user is signed in and wants to sign out while currently still being on a route which needs authentication, the redirect to the sso app does not work if `SignInType` equals `SignInType.Window`. The sign out request is cancelled and immediately afterwards the vue app tries to sign in again (since the user is currently on a route with necessary authentication) but this request also gets cancelled.

## Code to replicate issue
Repository: [vue-oidc-client_signout-issue](https://github.com/MisterFab1an/vue-oidc-client_signout-issue)

## Screenshots (when trying to sign out while being on the secured route)
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10604689/155147001-271cf27c-c7d9-457e-a761-9d6bb0768247.png">
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10604689/155147234-c8410146-b4c3-4f88-8905-a0345ceb3b05.png">

**Comment by soukoku** [comment]
Update to alpha.4 and use @click.prevent on the login/logout links to stop the url from changing will fix it.
