### ISSUE TITLE
oidc configuration options

### ISSUE THREAD

**Issue by cimtico** [soukoku/vue-oidc-client#8]
Why should these be hardcoded and not configurable?
`${appUrl}auth/signinsilent/${authName}`;
`${appUrl}auth/signinwin/${authName}`;
`${appUrl}auth/signinpop/${authName}`;

What happens if/when we want to use a provider that doesn't allow us to configure these endpoints?

**Comment by soukoku** [comment]
Should no longer be hard-coded in 0.3
