### ISSUE TITLE
How to set access_token to API client's headers and keep it in actual state after refreshing 

### ISSUE THREAD

**Issue by phyesix** [soukoku/vue-oidc-client#96]
In order to access an API a need to add the current token to API client's default headers for Axios. How can I?

**Comment by soukoku** [comment]
There should be an `accessToken` property on the auth instance if it had been requested during login.

[https://github.com/soukoku/vue-oidc-client/wiki/V1-Docs#using-it-in-vue-components](https://github.com/soukoku/vue-oidc-client/wiki/V1-Docs#using-it-in-vue-components)
